services:
  tea-frontend:
    container_name: tea-frontend
    build:
      context: .
      args:
        - REACT_APP_API_URL=https://teaform.ru/api
    environment:
      - REACT_APP_API_URL=https://teaform.ru/api
    # ports:
    #   - 8081:80
    #   - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true